name: Dev Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      compose_file: docker-compose.yml
      image_tag: ${{ github.sha }}
    secrets:
      EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
      EC2_KEY: ${{ secrets.DEV_EC2_KEY }}